name: Publish NPM Package

on:
  push:
    branches: [ $default_branch ]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Get node version
        id: nodenv
        run: echo "::set-output name=node-version::$(< .node-version)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nodenv.outputs.node-version }}
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          npm run build --if-present
          npm test

  publish:
    needs: [ build ]
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Get node version
        id: nodenv
        run: echo "::set-output name=node-version::$(< .node-version)"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nodenv.outputs.node-version }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
